baseURL = "http://localhost:1313"
languageCode = "en-us"
title = "FAB Electric & Trenching, L.L.C."
#theme = ""  # Make sure this line is empty or commented out
[[plugins]]
package = "@netlify/plugin-hugo"
